### ISSUE TITLE
Options are causing pass of tests who should failed 

### ISSUE THREAD

**Issue by nitzanashi** [palmerhq/cypress-image-snapshot#104]
**Expected Behaviour**
Tests should Failed for default values of options as described in README when given as a specific options.

**Actual Behaviour**
Tests are always passing and ignoring the given options.

**Description**
I have a test that failed for default setup:

```
// comands/comands.js

import {addMatchImageSnapshotCommand} from 'cypress-image-snapshot/command';
addMatchImageSnapshotCommand();
```

* Test failed Successfully:
```
  Running: visual/password-field.test.js...                                                (1 of 1) 


  Password Field
    ✓ complies to initial (10321ms)
    ✓ complies to inversed (822ms)
    ✓ complies to fullWidth (719ms)
    1) can have error


  3 passing (14s)
  1 failing

  1) Password Field can have error:
     Error: Image was 0.2612704918032787% different from saved snapshot with 204 different pixels.
See diff for details: ###
      at Context.cy.task.then (###)
```

![error diff](https://user-images.githubusercontent.com/13871150/65176120-d1031f80-da5c-11e9-9bde-2020c593ef1a.png)

---

* After Adding options to command Test is no longer failing
```
// comands/comands.js

import {addMatchImageSnapshotCommand} from 'cypress-image-snapshot/command';
addMatchImageSnapshotCommand({
    failureThreshold: 0.01, // threshold for entire image
    failureThresholdType: 'percent', // percent of image or number of pixels
    customDiffConfig: {threshold: 0.1}, // threshold for each pixel
    capture: 'viewport', // capture viewport in screenshot
});
```

```
Running: visual/password-field.test.js...                                                (1 of 1) 


  Password Field
    ✓ complies to initial (11665ms)
    ✓ complies to inversed (531ms)
    ✓ complies to fullWidth (418ms)
    ✓ can have error (1033ms)


  4 passing (14s)
```

**Comment by andtos90** [comment]
Hey @nitzanashi! I had a similar issue and I found something a little counterintuitive about `failureThreshold`, the percentage is expressed only with the decimal digits. In your case `failureThreshold: 0.01` is equal to 1%  but your test is failing with a lower percentage (0.26%).

**Solution:**
Just set `failureThreshold: 0.001` and your test will fail because 0.10% is lower than 0.26%.

If you want to know more, check this https://github.com/americanexpress/jest-image-snapshot#%EF%B8%8F-api

**Comment by nitzanashi** [comment]
@andtos90 , that worked for me, Cheers thanks!
