### ISSUE TITLE
Update snapshots and see difference output

### ISSUE THREAD

**Issue by sakwok** [palmerhq/cypress-image-snapshot#151]
I am aware of using the tag --env updateSnapshots=true to update my snapshots. However, I was wondering if it was possible to update snapshots and see the difference output in one run. I am running snapshot tests on ~100 pages and would like to avoid running the pipeline twice, once for seeing diffs and once for updating snapshots.

**Comment by danjor** [comment]
Any news on this subject ? I'm having the same issue.
