### ISSUE TITLE
Match cy.screenshot() filename behaviour

### ISSUE THREAD

**Issue by cb109** [palmerhq/cypress-image-snapshot#19]
https://docs.cypress.io/api/commands/screenshot.html#Naming-conventions

Newest cypress versions (3.0.2+) allow defining a nested screenshot filename like `cy.screenshot('dir1/dir2/foobar`) which automatically creates the `dir1` directory and its `dir2` subdirectory, storing `foobar.png` inside it. This pretty convenient e.g. when doing screenshots for `mobile/dashboard` and `desktop/dashboard`.

This plugin has its own naming scheme (test.title + name in kebab-case) and does not support this syntax for nested folders, it would be nice to match the default cypress behaviour :)

**Comment by crosscompile** [comment]
Nice, that is really convenient!  We should definitely support that behavior.

It looks like we will have to make slight change in how we determine the snapshot name, I'm hoping to open a PR later today.

**Comment by crosscompile** [comment]
Released in [v2.0.0](https://github.com/palmerhq/cypress-image-snapshot/releases/tag/v2.0.0).

Also with the major version bump we use Cypress' naming instead of our own custom kebab case.
