### ISSUE TITLE
how to take snapshot of whole page but ignore ONLY the content from a specific dom?

### ISSUE THREAD

**Issue by adamchenwei** [palmerhq/cypress-image-snapshot#35]
I know we can take snapshot of a specific dom or whole page. But when I want to snapshot a whole page without worry about specific content in a dom BUT want to retain its space as part of the whole page snapshot checking for the page as a whole. Is that doable with this plugin and how to do that may I ask?

thank you!

**Comment by renelux** [comment]
The screenshot method accepts the an option which is called blackout, this an array of elements that should be blacked out in the screenshot. As the plugin just utilizes the event that is triggered after `screenshot` you can use that option to blackout the content meaning it will get ignored.

```
cy.screenshot({
  blackout: ['.container_one', '.container_two']
})
```

https://docs.cypress.io/api/commands/screenshot.html#Arguments

**Comment by crosscompile** [comment]
@renelux is correct the `blackout` option should work.

You can also pass the `blackout` option directly to `cy.matchImageSnapshot` and it will be used when taking a screenshot:

```
cy.matchImageShapshot({
  blackout: ['.container_one', '.container_two']
})
```

Closing the issue, feel free to reopen if this suggestion doesn't work.

**Comment by adamchenwei** [comment]
awesome. thanks guys!
