### ISSUE TITLE
Don't fail until the end

### ISSUE THREAD

**Issue by cdeutsch** [palmerhq/cypress-image-snapshot#37]
It'd be great to have an option to not immediately throw an error when the snapshot is different.

It's a slow development cycle to run a bunch of tests and then hit one issue, fix it, then repeat.

**Comment by crosscompile** [comment]
I agree this would really benefit the development cycle.

My first thought is that it might be difficult to throw an error only after all snapshots have been run, but I need to read through the Cypress docs more to see if they expose any functionality to do so.

Another option might be to expose something like `--diff-only` that won't fail any snapshot tests and only generate diffs.  That way you could run the tests once to see all the diffs, fix them, and run the tests again.

**Comment by crosscompile** [comment]
Closing this for now as I'm not aware of a method to cause a test to fail from the reporting step.
