### ISSUE TITLE
Screenshot was NaN% different from saved snapshot with undefined different pixels.

### ISSUE THREAD

**Issue by James-E-Adams** [palmerhq/cypress-image-snapshot#43]
Hey!

This is very very cool. Nice work :) 

I just gave it a crack in our project but getting the following:
```
Screenshot was NaN% different from saved snapshot with undefined different pixels.
  See diff for details: undefined
```

![screen shot 2018-11-15 at 12 12 41 pm](https://user-images.githubusercontent.com/9067274/48523279-e4d77580-e8cf-11e8-8376-24fea2d9098f.png)

It's saving the screenshot correctly but haven't got a run to pass yet with/without a saved image available in the screenshots dir.

Is there anything special I have to do on first run? I've tried with both suggested env options 

`updateSnapshots=true failOnSnapshotDiff=false` but no luck getting the test to pass.

I also followed the suggested instructions,

and have tried the following options in my commands:

```
addMatchImageSnapshotCommand({
  capture: 'viewport', // capture viewport in screenshot
})
```

```
addMatchImageSnapshotCommand({
  failureThreshold: 0.03, // threshold for entire image
  failureThresholdType: 'percent', // percent of image or number of pixels
  customDiffConfig: { threshold: 0.1 }, // threshold for each pixel
  capture: 'viewport', // capture viewport in screenshot
})
```

Thanks for any help you can provide.

**Comment by crosscompile** [comment]
Thanks!

In addition to `addMatchImageSnapshotCommand`, are you also adding the plugin?

It should be added in `/cypress/plugins/index.js` with:
```js
const {
  addMatchImageSnapshotPlugin,
} = require('cypress-image-snapshot/plugin');

module.exports = (on, config) => {
  addMatchImageSnapshotPlugin(on, config);
};
```

**Comment by James-E-Adams** [comment]
Yup! Have that in there.

**Comment by crosscompile** [comment]
Hmm so on the first run `cy.matchImageSnapshot` should not cause any tests to fail and just record snapshot images to use on later runs.

I just tried a first run locally without any issues by installing https://github.com/palmerhq/cypress-image-snapshot/tree/master/examples, removing `/cypress/snapshots`, and running the tests.

Would you mind sharing your `cypress.json` config and Cypress version?  I'm wondering if there is an edge case with a specific setup that we're not handling.

**Comment by James-E-Adams** [comment]
Interesting - I just tried deleting `cypress/snapshots` and trying with/without args to `cy.matchImageSnapshot()` and still got the same error.

Sure:
```json
{
  "$schema": "https://on.cypress.io/cypress.schema.json",
  "baseUrl": "http://localhost:3000",
  "viewportWidth": 1000,
  "viewportHeight": 1500,
  "video": true,
  "defaultCommandTimeout": 20000,
  "ignoreTestFiles": "*.inprogress.js",
  "projectId": REDACTED,
  "reporter": "junit",
  "reporterOptions": {
    "mochaFile": "cypress/results/results-[hash].xml",
    "toConsole": "false"
  }
}
```

Cypress v3.0.1

**Comment by crosscompile** [comment]
Ah okay so since Cypress's screenshot functionality has changed a lot across 3.x.x versions, you'll need to use `cypress-image-snapshot@>=1.0.0 <2.0.0` with `cypress@3.0.1` or upgrade Cypress.

**Comment by crosscompile** [comment]
Also just [added a note to the README](https://github.com/palmerhq/cypress-image-snapshot#cypress-version-requirements) as this is confusing behavior.

**Comment by James-E-Adams** [comment]
Woo! You hit the nail on the end - that fixed it. I think we can now close this issue with the note in the README. As an added bonus, upgrading Cypress fixed a long-term issue I was having on my machine - so thanks for being the impetus for upgrading. 🎉

**Comment by nani554** [comment]
@crosscompile Hi Jack, the issue is still there, because iam using 
`on(after:screenshot) event & addMatchImageSnapshotPlugin(on, config);`  in **plugins/index.js**,
Either the code written in after screenshot function or cypress image snapshot is working, both are not working simultaniously. 
please look into this issue which i have posted in cypress
https://github.com/cypress-io/cypress/issues/6648

versions: 
cypress: ^3.8.3,
cypress-image-snapshot: ^3.1.1
