### ISSUE TITLE
Can't find existing snapshots

### ISSUE THREAD

**Issue by James-E-Adams** [palmerhq/cypress-image-snapshot#48]
Hi! Me again. 

I haven't had a chance to dig in as deeply as I'd like to yet but for some reason it can't find existing snapshots and thinks it's doing a new run every time. It doesn't override the existing snapshot -it just creates a new one and never does any diff.

I.e 
`cy.matchImageSnapshot('potato')`
 
for a spec named `cheese.spec.js`

results in

`screenshots/cheese.spec.js/potato.png` 
`snapshots/cheese.spec.js/potato.snap.png` 

on the first go round.

And then second go round it generates:

`screenshots/cheese.spec.js/potato (1).png` 
`snapshots/cheese.spec.js/potato (1).snap.png` 

and does no diffing. 

I've also set up `mocha-multi-reporters` but no luck with the reporting. 
(Maybe because it's not doing any diffing so it has nothing to report)

Options are standard (from `README`) - and commands/plugins are set up as discussed earlier.

**Comment by James-E-Adams** [comment]
I've also confirmed in the debugger that `updateSnapshots` is false at runtime.

**Comment by kodedninja** [comment]
Just wanted to open an issue for this.

As I've experienced it only happens if you run the tests from the Cypress GUI (`cypress open`) and it works fine from the CLI. Also, not sure if it comes from Windows handling copying files differently.

**Comment by crosscompile** [comment]
Just read over the Cypress screenshot [naming conventions](https://docs.cypress.io/api/commands/screenshot.html#Naming-conventions) again and it looks like if a screenshot has an identical name to one that exists, a number will be appended.

When using `cypress run` this isn't an issue since by default it deletes the contents of the screenshots folder, but with `cypress open` this isn't the case.

I think we should delete the screenshot programmatically since we are saving a copy as a snapshot anyways.  Added that functionality in #49.

**Comment by crosscompile** [comment]
Released this in [`v2.3.2`](https://github.com/palmerhq/cypress-image-snapshot/releases/tag/v2.3.2), let me know if you still have issues!

**Comment by crosscompile** [comment]
@James-E-Adams I also just realized the issue you mentioned with `mocha-multi-reporters` is a slightly different issue, released a fix for that in [`v2.3.3`](https://github.com/palmerhq/cypress-image-snapshot/releases/tag/v2.3.3).

Thanks for bearing with me on these issues, there are a lot of moving parts between Cypress, Mocha, and Jest 😅.

**Comment by kodedninja** [comment]
Thanks a lot for the quick fix!

**Comment by James-E-Adams** [comment]
@crosscompile Haha nice work! I'll check it out on Monday but thanks a lot for the quick updates. 🎉 🌮

**Comment by James-E-Adams** [comment]
Cool! All working great. Thanks 🎉 

Would it be useful for me to open a PR with some docs on the multi-reporter setup?

**Comment by crosscompile** [comment]
@James-E-Adams that would be great, I had to look up how to do so when I was debugging 😄.

Opened #54 if you feel like tackling it.

**Comment by James-E-Adams** [comment]
Done! Opened https://github.com/palmerhq/cypress-image-snapshot/pull/55.
