### ISSUE TITLE
screenshot

### ISSUE THREAD

**Issue by jaredpalmer** [palmerhq/cypress-image-snapshot#5]
![app-should-visit-the-app-diff](https://user-images.githubusercontent.com/4060187/41941848-4a931f8e-796b-11e8-848e-8a6c85cd26d0.png)

**Comment by jaredpalmer** [comment]
![app-should-visit-the-app-diff 1](https://user-images.githubusercontent.com/4060187/41942163-72c8c20a-796c-11e8-9149-c295341864d3.png)

**Comment by jaredpalmer** [comment]
![cypress-image-snapshot](https://user-images.githubusercontent.com/4060187/41942389-5a6705ae-796d-11e8-8003-fadbf7ccf43d.gif)

**Comment by crosscompile** [comment]
<img width="951" alt="screen shot 2018-11-14 at 5 52 05 pm" src="https://user-images.githubusercontent.com/1153686/48518011-303d4580-e836-11e8-83ed-776acae78f9f.png">
