### ISSUE TITLE
CHANGELOG missing

### ISSUE THREAD

**Issue by MichaelDeBoey** [palmerhq/cypress-image-snapshot#56]
I just saw the package is updated to `v2.3.5`, but I can't find any CHANGELOG to check out the changes.

Would you guys be so kind to provide us with a decent CHANGELOG please? 🙂

Thanks for all your hard work! 🙂

**Comment by MichaelDeBoey** [comment]
Ping @jaredpalmer

**Comment by crosscompile** [comment]
Yes we should definitely maintain a CHANGELOG 👍.

I'll make sure we document any releases going forwards, trying to find a bit of time to document changes retroactively as well.

**Comment by crosscompile** [comment]
I added a summary of changes for the [`v3.0.0`](https://github.com/palmerhq/cypress-image-snapshot/releases/tag/v3.0.0) release, closing this as I'll keep documenting changes there.
