### ISSUE TITLE
Uncaught referenceError: options is not defined

### ISSUE THREAD

**Issue by j1348** [palmerhq/cypress-image-snapshot#62]
I am getting this error probably due to the `commands.js` file

```
import { addMatchImageSnapshotCommand } from 'cypress-image-snapshot/command';

addMatchImageSnapshotCommand(options);
```

**Comment by crosscompile** [comment]
Ah the example in the README is a little misleading, if you don't have any custom options you should omit `options`:

```js
import { addMatchImageSnapshotCommand } from 'cypress-image-snapshot/command';

addMatchImageSnapshotCommand();
```

I'll remove that so that a direct copy and paste works.

**Comment by j1348** [comment]
this would be helpful.

**Comment by j1348** [comment]
I have this problem with `cypress@3.1.4` and not with `cypress@3.1.1`
