### ISSUE TITLE
cachePath does not exists

### ISSUE THREAD

**Issue by shaurgon** [palmerhq/cypress-image-snapshot#65]
cachePath uses static path `cypress/.snapshot-report`.  
it's worked good if you run tests from root of project.  
But we run tests from subproject in `cypress` folder,  
path `cypress/cypress...` does not exists and tests fails.  
This is a reason for disable reporter =(

Can you make this path more configurable from options?

**Comment by crosscompile** [comment]
I opened #68 to address this issue, but I wasn't able to actually run cypress outside the root of any of my projects.  

@shaurgon can you share an example folder structure and the command you're running  when you see this error?

**Comment by shaurgon** [comment]
Sorry for your waiting.
Our structure:
```
projectname
└ src
└ cypress
  └ snapshots
    ...
  └ package.json
└ package.json
```
For start tests we use `cypress/package.json`, then process.cwd() is equal `/projectname/cypress/`

**Comment by shaurgon** [comment]
Also `cypress.json` placed to `projectname/cypress` too and all path options redefined

**Comment by smilemoreall** [comment]
I have same problem, but Cypress have another path `projectname/tests/e2e`

**Comment by alexisponcet** [comment]
Same problem as smilemoreall. My project structure use 'e2e' instead of 'cypress'
