### ISSUE TITLE
Snapshots sometimes captured at smaller size

### ISSUE THREAD

**Issue by PTaylour** [palmerhq/cypress-image-snapshot#67]
I'm sometimes seeing failed tests where the snapshots look to be the same, but at different resolutions.

Has anyone else experienced this?

![playback at time 0 5 diff](https://user-images.githubusercontent.com/3678476/53601066-189a8a80-3ba3-11e9-93f5-03e8b13806ed.png)

`index.html`
```
    <canvas id="canvas" width="1920" height="1080" style="width: 500px;"></canvas>
```

`test.spec.js`
```
// ...  code to render image on canvas. 
cy.get("#canvas").matchImageSnapshot()
```

**Comment by crosscompile** [comment]
I have experienced this issue intermittently when switching between `cypress run` and `cypress open`.  Were both these screenshots taken in the same mode?

https://github.com/cypress-io/cypress/issues/1309 might also be related.

**Comment by PTaylour** [comment]
They were taken with the different modes for me too. 

I did update snapshots with `run`

then using `run` again passed

but using `open` results in the failure.

Have you tried any workarounds?

**Comment by crosscompile** [comment]
I haven't tried this myself, but this seems like a promising workaround: https://github.com/cypress-io/cypress/issues/495#issuecomment-472723434.

**Comment by PTaylour** [comment]
That looks great, shall try it out!

**Comment by rodoabad** [comment]
This is also happening to me too.

`run` and `open` produces different snapshots.

**Comment by rodoabad** [comment]
@crosscompile that "workaround" does not work for me. Did it work for you?

**Comment by crosscompile** [comment]
@rodoabad I haven't had a chance to try it out yet.

**Comment by PTaylour** [comment]
I tried it quickly and it didn't work for me

**Comment by littletower** [comment]
Did anyone come up with a solution to solve this? The workaround did not work for me either

**Comment by edelgado** [comment]
This is hugely problematic for us. Can we discard that this is an issue with this plugin though?

**Comment by PTaylour** [comment]
Yep happy to close in favour of https://github.com/cypress-io/cypress/issues/33244 if this a cypress `cy.screenshot` issue.

**Comment by PTaylour** [comment]
This obviously still affects this plugin though. Feel free to re-open if this issue is a useful way to track progress.

**Comment by rodoabad** [comment]
@PTaylour are you sure that's the right issue? It's a 404.
