### ISSUE TITLE
how cypress-image-snapshot integrate with mochawesome html report?

### ISSUE THREAD

**Issue by gtycherry** [palmerhq/cypress-image-snapshot#70]
Does anybody know how cypress-image-snapshot integrate with mochawesome html report?

**Comment by crosscompile** [comment]
@gtycherry are you wondering if you can use a reporter alongside cypress-image-snapshot?  Or if cypress-image-snapshot can add images to the reporter?

We also have a section in the readme about [using multiple reporters](https://github.com/palmerhq/cypress-image-snapshot#multiple-reporters).

**Comment by crosscompile** [comment]
Closing this issue, feel free to re-open if there are still issues.
