### ISSUE TITLE
screenshot problem under linux

### ISSUE THREAD

**Issue by zquancai** [palmerhq/cypress-image-snapshot#71]
I run the test under MacOS and took a screenshot. However, when I run the same test on Linux(cypress docker), the screenshot comparison failed. I see the comparison result, probably because of the problem of screen resolution.

**Comment by rodoabad** [comment]
@zquancai are you having problems with the font?

**Comment by crosscompile** [comment]
I have had this issue as well, I think the best way to ensure consistent snapshots locally and on CI is to run your tests in a container, Cypress has [some docs about using containers](https://docs.cypress.io/examples/examples/docker.html#Images).


Alternatively if you're not interested in reworking your test setup at the moment, I have also had some success with tweaking the app styles to be more consistent across local and CI.

I'm not proud of this code but here is what I've tried in my Cypress commands:

```ts
function hackScreenshot() {
  const iframe = window.parent.document.querySelector(
    "iframe[id^='Your App']"
  );
  const contentDocument = iframe && iframe.contentDocument;

  if (contentDocument) {
    const style = contentDocument.createElement('style');
    style.type = 'text/css';
    style.appendChild(
      contentDocument.createTextNode(
        '* { font-family: Helvetica !important; } html { overflow-y: hidden; }'
      )
    );
    contentDocument.head.appendChild(style);
    return style;
  }

  return false;
}

function cleanupHackScreenshot(style) {
  if (style) {
    style.remove();
  }
}

function hackAndMatchSnapshot(options) {
  cy.hackScreenshot();
  cy._snapshot(options);
  cy.cleanupHackScreenshot();
}
```

**Comment by zquancai** [comment]
> @zquancai are you having problems with the font?

Yes，you can install necessary font in your private image base on official image.
