### ISSUE TITLE
how to continue the diff work when there are more than one image changed

### ISSUE THREAD

**Issue by gtycherry** [palmerhq/cypress-image-snapshot#73]
Currently found image-snapshot stop diff work once there is one image diff found. Can image-snpshot support diff work for all the images?

**Comment by crosscompile** [comment]
@gtycherry can you try running with the following flags:

```bash
cypress:run --reporter cypress-image-snapshot/reporter --env failOnSnapshotDiff=false
```

This will run all of your snapshots diffs, output their differences, but not fail the test at the first diff.
