### ISSUE TITLE
Snapshots aren't being updated with `--env updateSnapshots=true`

### ISSUE THREAD

**Issue by rodoabad** [palmerhq/cypress-image-snapshot#74]
When running Cypress with `--env updateSnapshots=true`, snapshots aren't being updated and diff snapshots are also not being deleted.

Using this with version 3.x.

**Comment by crosscompile** [comment]
I tried this in the `/examples` directory by running:
```bash
npm run start
```
and in another terminal:
```bash
npm run cypress:run -- --env updateSnapshots=true
```
And was able to see that the snapshots were updated.  Note that with `npm` you need to add a `--` to pass flags to the underlying command.

If that wasn't your issue let me know!

**Comment by rodoabad** [comment]
@crosscompile thanks, I'm going to try this out and close the issue if it fixes it.

**Comment by crosscompile** [comment]
Closing this issue, feel free to re-open if the fix did not work.
