### ISSUE TITLE
how to ignore or exclude a certain area of the page from diff comparison but still retain the screenshot of the whole page? 

### ISSUE THREAD

**Issue by adamchenwei** [palmerhq/cypress-image-snapshot#76]
is that even possible?

**Comment by ferdiesletering** [comment]
Don't think that is possible atm. I had a similar use case to prevent dynamic content ruining the test. 
In my example, iframes are excluded from the screenshots.

I've added the following to command.js

```
import { addMatchImageSnapshotCommand } from 'cypress-image-snapshot/command';

addMatchImageSnapshotCommand({
    blackout: ['iframe']
});
```

Maybe it helps

**Comment by crosscompile** [comment]
@adamchenwei I would try using Cypress' `screenshot` options like so:

`cy.matchImageSnapshot({ blackout: 'iframe', capture: 'fullPage' })`

You can read more about their `screenshot options here: https://docs.cypress.io/api/commands/screenshot.html#Arguments.  Feel free to reopen if that doesn't solve your issue.

**Comment by xu3u4** [comment]
Hi @crosscompile
I tried to use `cy.matchImageSnapshot({ blackout: ['img'] })` but somehow it doesn't work. 
If I just use `cy.screenshot({ blackout: ['img'] })`, it works as expected. The image tags are blackedout.

**Comment by patryksniegucki** [comment]
Hey, do you know why it's not working on cy.matchImageSnapshot ??
