### ISSUE TITLE
Cannot read property '1' of null     at Object.matchImageSnapshotPlugin [as handler]

### ISSUE THREAD

**Issue by mcmc4519** [palmerhq/cypress-image-snapshot#77]
Hi!
On run test, and in test I run 
`cy.matchImageSnapshot(`category_with_filters_${label}`);`

I have error, http://prntscr.com/n7jec5

Can you help me?

**Comment by mcmc4519** [comment]
somebody have same error?

**Comment by crosscompile** [comment]
@mcmc4519 can you share your `cypress.json` configuration?  I'm wondering if there is a configuration edge case we didn't handle.

**Comment by mcmc4519** [comment]
> @mcmc4519 can you share your `cypress.json` configuration? I'm wondering if there is a configuration edge case we didn't handle.

![image](https://user-images.githubusercontent.com/38068389/57643279-0638c600-75c2-11e9-91b3-fb33374655c7.png)

**Comment by crosscompile** [comment]
I think this issue should be fixed in [v3.0.2](https://github.com/palmerhq/cypress-image-snapshot/releases/tag/v3.0.2).  Feel free to reopen if you're still facing the issue.

**Comment by fshchudlo** [comment]
@crosscompile 
Hello. I see same error **after** update to 3.0.2 (and 3.1.0). No matter with or without `screenshotsFolder` option specified.

**Comment by mfolnovic** [comment]
It seems this fix broke windows support - you are trying to match with Regex that contains `\`.

**Comment by crosscompile** [comment]
Sorry about that, looks like the regex used doesn't account for Window's file paths.

**Comment by crosscompile** [comment]
Released a fix in [v3.1.1](https://github.com/palmerhq/cypress-image-snapshot/releases/tag/v3.1.1).  I don't have a Windows computer handy to fully test if someone is able to confirm the fix works.

**Comment by fshchudlo** [comment]
Check it on Windows. Everything is ok. Thank you!
