### ISSUE TITLE
Screenshot fullpage

### ISSUE THREAD

**Issue by CassieRyu** [palmerhq/cypress-image-snapshot#78]
Cypress support full page screenshot now. (Implement it by scrolling to the top, then taking a screenshot, scrolling, taking a screenshot, and so on, then stitching them together.)

Is there anyway we are able to compare full page screenshot for regression?
Refer: https://github.com/cypress-io/cypress/issues/1424

**Comment by adamchenwei** [comment]
that feature seems more more of code snapshot? @CassieRyu  not an image shot... right? I just read through the post a bit more.

**Comment by kylemh** [comment]
I just changed `capture` to `'fullPage'` and it's working fine.

**Comment by crosscompile** [comment]
As @kylemh mentioned using `capture` should do the trick:

```js
cy.matchImageSnapshot({ capture: 'fullPage' }).
```

The [options section of our README](https://github.com/palmerhq/cypress-image-snapshot#options) mentions how you can pass any Cypress `screenshot` options to `matchImageSnapshot`. You can read more about all the options they support in the Cypress docs: https://docs.cypress.io/api/commands/screenshot.html#Arguments.
