### ISSUE TITLE
Upgrade `jest-image-snapshot` dependency.

### ISSUE THREAD

**Issue by edelgado** [palmerhq/cypress-image-snapshot#84]
The current version specified in [`package.json`](https://github.com/palmerhq/cypress-image-snapshot/blob/master/package.json#L25) does not support the `diffDirection` option which was added recently in [`2.8.1`](https://github.com/americanexpress/jest-image-snapshot/releases/tag/v2.8.1).

It would be great to have the option to stack the diff images vertically. Thanks!

**Comment by crosscompile** [comment]
Released in [v3.1.0](https://github.com/palmerhq/cypress-image-snapshot/releases/tag/v3.1.0).

**Comment by edelgado** [comment]
That was quick! Thanks! 🙂
