### ISSUE TITLE
Example fails to find image

### ISSUE THREAD

**Issue by robcaldecott** [palmerhq/cypress-image-snapshot#9]
I just tried the example repo using the latest Cypress (3.0.2) on my MacBook and it fails with the following error:

```bash
Error: ENOENT: no such file or directory, open '/Users/rob/Projects/cypress-image-snapshot/examples/cypress/screenshots/app-should-visit-the-app.png'
```

On my Mac the screenshot is actually located in:

```bash
/Users/rob/Projects/cypress-image-snapshot/examples/cypress/screenshots/All Specs/app-should-visit-the-app.png
```

So it looks like the plugin is expecting the file to be in a different location. To reproduce simply follow the instructions for the example:

```bash
git clone https://github.com/palmerhq/cypress-image-snapshot.git
cd cypress-image-snapshot/examples
npm install
npm run examples
```

**Comment by crosscompile** [comment]
It looks like Cypress screenshot logic [significantly changed](https://github.com/cypress-io/cypress/issues/1826) in `3.0.2` which is causing this failure.  I think we will need to start using the new `after:screenshot` API to reliably get the screenshot paths.

In the meantime the example should work if you explicitly `npm install cypress@3.0.1`.
