### ISSUE TITLE
Duplicated bottom of image

### ISSUE THREAD

**Issue by baronvonbirra** [palmerhq/cypress-image-snapshot#92]
Hi!

When taking snapshots, it looks like the bottom of the image of the screenshots are duplicated. Here an example:
![image](https://user-images.githubusercontent.com/18036304/60518343-a0271000-9ce1-11e9-83dc-ca69256829e4.png)
There should be just 3 buttons at the bottom of the page, not 6: the other 3 are duplicated. The same is happening to me in all screenshots I take. 

Why is this happening?

Thanks!

**Comment by crosscompile** [comment]
Huh that is strange, does this also happen when you use `cy.screenshot()` directly?

**Comment by baronvonbirra** [comment]
Yep, I'm afraid... I managed to "fix" this and now is working as a gem. I'll leave you some info as I'm not sure what could be failing, in case someone else finds the same problem, but I was using `macbook-15 | 1440 | 900` viewport dimensions for my tests, and after changing it for something more generic (1280x720) it now works perfectly! 
Thanks!

**Comment by Robo-Rin** [comment]
To others coming here, what I found worked for me was explicitly setting `{ capture: 'viewport' }` which is a native Cypress [`cy.screenshot()` option](https://docs.cypress.io/api/commands/screenshot#Arguments) that gets passed through.

i.e.:
```js
cy.matchImageSnapshot('SomeName', { capture: 'viewport' })
```
