### ISSUE TITLE
Difference in color is not considered in image snapshot

### ISSUE THREAD

**Issue by cpandit201** [palmerhq/cypress-image-snapshot#97]
**Problem**: Colors should be considered as a part of the snapshot image difference  

**Issue:**  A difference in color is not considered as a failing point for Cypress Image Snapshot
PFB Pictures

PFB the images
**Expected**: Image diff should FAIL as the expected colors are different
**Actual**: Image difference is PASSED.
 
Please let me know how do I enable inclusion of Color in image diff?  

![image](https://user-images.githubusercontent.com/42322819/63755834-faed7a00-c8d4-11e9-9ea2-9611cdd13324.png)

![image](https://user-images.githubusercontent.com/42322819/63755898-0f317700-c8d5-11e9-96c0-f69903fb4e45.png)

I have overridden below Image Diff configuration let me know if this is the issue:
```
//<cypress-root>/support/commands.js

import { addMatchImageSnapshotCommand } from 'cypress-image-snapshot/command';

addMatchImageSnapshotCommand({
  failureThreshold: 0.9, // threshold for entire image
  failureThresholdType: 'percent', // percent of image or number of pixels
});
 ```

**Comment by sebinsua** [comment]
Relatively sure that this is a [`failureThreshold`](https://github.com/americanexpress/jest-image-snapshot/blob/c6a0bf6e399277ee8fce71d32eeaf4abaa2e8d26/src/diff-snapshot.js#L174) of 90%!

**Comment by cpandit201** [comment]
@sebinsua Thanks for clarification 👍
